ublox_gps_node:
  ros__parameters:
    debug: 0
    device: /dev/ttyGps # smc device name
    frame_id: gps
    uart1:
      baudrate: 115200
      in: 35
      out: 35

    rate: 5.0
    # TMODE3 Config
    tmode3: 0                   # Survey-In Mode

    inf:
      all: true                   # Whether to display all INF messages in console
    publish:
      all: true
      aid:
        hui: false
      nav:
        posecef: false
        relposned: True
    gnss:
      sbas: True
      galileo: True
      beidou: True
      qzss: True
      glonass: True

